spring:
  application:
    name: load-balancer

server:
  port: 8888

converter:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:9092,localhost:9996
    ServerListRefreshInterval: 15000
